### ISSUE TITLE
出错 引擎失败

### ISSUE THREAD

**Issue by WXH-qingmei** [hiroi-sora/GapTree_Sort_Algorithm#2]
qml: set mission state:   init
引擎启动失败！ [Error] OCR init fail. Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx', 'cls': 'ch_ppocr_mobile_v2.0_cls_infer.onnx', 'rec': 'rec_ch_PP-OCRv4_infer.onnx', 'keys': 'dict_chinese.txt', 'doAngle': 0, 'mostAngle': 0, 'maxSideLen': 1024, 'numThread': 4}
[Errno 2] No such file or directory: 'nul'   打不开程序  使用cli也这样出现  大佬 这是什么情况？CPU太低了？

**Comment by hiroi-sora** [comment]
你是想尝试自己的样例是吧，请先将引擎组件 [RapidOCR-json](https://github.com/hiroi-sora/RapidOCR-json/releases/tag/v0.2.0) 下载下来，放到本项目本地的 `RapidOCR_json` 目录中。
