### ISSUE TITLE
如果已通过模型获取到版面的layout（包含bbox及block类型），只想对layout排序，该如何调用获取顺序

### ISSUE THREAD

**Issue by enymfc25173** [hiroi-sora/GapTree_Sort_Algorithm#3]
如题，已star，求解答

**Comment by hiroi-sora** [comment]
你好~

我觉得直接调用本算法即可，直接传入所有block，不用管类型，获取所有元素的先后排序。

如果你想避免一些非正文的跨列元素的干扰（如图像、表格、注释、页眉页脚等block类型），可以先删除这些block，仅对`标题`+`正文`进行一次排序。然后，再根据原始坐标，将其他元素插入`原始左上角坐标距离`最近的正文行中。

或者，也可以将其他元素插入当前段落的最后一行之后，形成这样的结构：
```
标题（第一段）
正文
正文
正文
表格
图片
标题（第二段）
正文
正文
表格
```
